### PR TITLE
remove restriction against generating JSON with an atomic root value

### LINKED ISSUE #121: `pretty_print` raises errors when asked to print any value other than an array or object
e.g.:

```
utop # Format.printf "%a@." (Yojson.Basic.pretty_print ~std:true) (`Int 5);;
Exception:
Yojson.Json_error
 "Root is not an object or array as requested by the JSON standard"
```
My first question is, where does the standard request that JSON values aside from objects and arrays not be printed? Looking at [json.org](http://json.org), and the actual [ECMA standard](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf), I don't see any language to this effect. On the contrary, the ECMA document states plainly that "A JSON value can be an object, array, number, string, true, false, or null", and the quasi-BNF on the side of json.org is pretty clear that any of these things is a valid JSON value.

Beyond litigating the specification though, the current behaviour is just incredibly unhelpful. Javascript runtimes happily `parse` and `stringify` non-object and non-array "root" values, and OCaml programs need to deal with the same. To that end, I consistently carry around these functions so I can serialize JSON values as required by APIs and other programs (with the understanding that my treatment of strings via Format's `%S` might actually be slightly off):

```ocaml
let pp_json f fmt =
  let open Format in
  function
  | `Null -> pp_print_string fmt "null"
  | `Int v -> pp_print_int fmt v
  | `Float v -> pp_print_float fmt v
  | `String v -> fprintf fmt "%S" v
  | `Bool v -> pp_print_bool fmt v
  | v -> fprintf fmt "@[%a@]" f v

let pp_json_basic = pp_json (Yojson.Basic.pretty_print ~std:true)

let pp_json_safe = pp_json (Yojson.Safe.pretty_print ~std:true)
```

Can we remove this limitation?

### PR DESCRIPTION
**Pull request by cemerick**
This fixes #121.

Unfortunately no tests to add; as it stands, there's a only a single monolithic test for pretty-printing, and the simple change doesn't seem to warrant setting up a new harness.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Could you add a note in the changelog? Not that I expect things to be breaking a lot but it would probably be helpful to users to know since when the behavior was improved.

**Comment by cemerick** [comment]
Sure, my bad, just updated to include a changelog entry.

File: lib/pretty.ml [hunk 1]
```diff
@@ -49,11 +49,7 @@ and format_field std out (name, x) =
   Format.fprintf out "@[<hv2>%s: %a@]" (json_string_of_string name) (format std) x
 
 let pp ?(std = false) out x =
-  if std && not (is_object_or_array x) then
```
Comment (Leonidas-from-XIV) [inline lib/pretty.ml:52]: It looks like `is_object_or_array` is not used anymore (since these were the only uses of it and I can't imagine where else this would be useful), could you remove it too? Avoids us dragging around dead code.

**Review by Leonidas-from-XIV — CHANGES_REQUESTED** [review]
Looks good, I think we can remove even more dead code.

We just fixed the CI (finally), could you rebase on current master?

File: lib/pretty.ml (hunk 1 above)
Comment (cemerick) [reply lib/pretty.ml:52]: Sure, done :+1:

**Review by Leonidas-from-XIV — APPROVED** [review]
